name: apna_mandi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  http: ^1.3.0 # Updated http package for API calls
  image_picker: ^1.0.4
  provider: ^6.1.1 # Added provider package for state management
  logging: ^1.2.0
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  intl: any
  easy_localization: ^3.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/translations/
